#! /usr/bin/env python
# encoding: utf-8

APPNAME = '{{cookiecutter.name}}'
VERSION = '0.0.0'


def build(bld):

    bld.env.append_unique(
        'DEFINES_STEINWURF_VERSION',
        '{{cookiecutter.version_namespace}}="{}"'.format(
            VERSION))

    bld.recurse('src/{{cookiecutter.name}}')

    if bld.is_toplevel():

        # Only build tests when executed from the top-level wscript,
        # i.e. not when included as a dependency
        bld.recurse('test')
        bld.recurse('examples')
