#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features="cxx test",
    source=["{{cookiecutter.name}}_tests.cpp"] + bld.path.ant_glob("src/*.cpp"),
    target="{{cookiecutter.name}}_tests",
    use=["{{cookiecutter.name}}", "gtest"],
)
